micronaut:
  application:
    name: pageApp
  executors:
    consumer:
      type: fixed
      nThreads: 6

rabbitmq:
  uri: amqp://localhost:5672

aws:
  access_key_id: ${AWS_ACCESS_KEY_ID}
  secret_access_key: ${AWS_SECRET_ACCESS_KEY}
  s3:
    bucket: ${AWS_S3_BUCKET}
    region: ${AWS_S3_REGION}

